<style>
.sm-wrap, .sm-wrap .sm-cell, .sm-cell { background-color: #ffffff !important; }
[data-ogsb] .sm-wrap, [data-ogsb] .sm-wrap .sm-cell, [data-ogsb] .sm-cell { background-color: #ffffff !important; }
u + .sm-body .sm-wrap, u + .sm-body .sm-cell { background-color: #ffffff !important; }
@media (prefers-color-scheme: dark) {
body, .sm-body, .sm-wrap, .sm-cell { background-color: #ffffff !important; }
}
</style>
<p style="text-align: center;"><span style="color: #004994;"><em><strong><br><img style="display: block; margin-left: auto; margin-right: auto;" src="https://email-app.subaru.ro/uploads/1789461727-GMQ2MYtuJd5J.png" alt="" width="500" height="286"><br><br></strong></em></span></p>
<p class="MsoNormal" style="text-align: center; max-width: 500px; margin: 0 auto;"><span style="color: #004994;"><strong><span style="font-size: 13pt; font-family: Aptos, sans-serif;">Dragi clienți,<br><br></span></strong></span></p>
<p class="MsoNormal" style="text-align: center; max-width: 500px; margin: 0 auto;"><span style="font-size: 13pt; color: #004994; font-family: Aptos, sans-serif;">&Icirc;n primul r&acirc;nd, vreau să vă mulțumesc &icirc;n numele meu și al tuturor colegilor pentru &icirc;ncrederea pe care ne-o acordați și pentru că ne lăsați să avem grijă de mașinile dumneavoastră. <br>&Icirc;n ultima perioadă, cu toții am resimțit creșterea semnificativă a costurilor. Tocmai de aceea ne-am &icirc;ntrebat cum putem pune resursele și vizibilitatea noastră la dispoziția clienților Rădăcini, pentru a vă oferi un beneficiu concret, care să vă fie cu adevărat util și care să nu presupună niciun cost pentru voi.</span><br><br><span style="color: #004994;"><img src="https://email-app.subaru.ro/uploads/1789461902-cpGIKXJ7s8oL.png" alt="" width="500" height="76"></span><br><br></p>
<p class="MsoNormal" style="text-align: center; max-width: 500px; margin: 0 auto;"><span style="font-size: 13pt; color: #004994; font-family: Aptos, sans-serif;">Website-ul Rădăcini este vizitat zilnic de zeci de mii de clienți interesați de automobile, iar prin această facilitate veți putea ajunge la potențiali cumpărători fără să plătiți taxe de publicare sau abonamente lunare.</span></p>
<p class="xmsonormal" style="text-align: center;"><span style="color: #004994;"><img src="https://email-app.subaru.ro/uploads/1789462021-PTWSrdEM3fnl.png" alt="" width="500" height="119"></span></p>
<p style="text-align: center;"><a href="https://radacini.ro/"><span style="color: #004994;"><img role="presentation" src="https://email-app.subaru.ro/uploads/1789463731-iagtY7MZSire.png" alt="" width="500" height="117"></span></a></p>
<p style="text-align: center; max-width: 500px; margin: 0 auto;"><span style="color: #004994;"><span style="font-size: 13pt; font-family: Aptos, sans-serif;">Știm că &icirc;n această perioadă fiecare leu contează. Sperăm ca acest serviciu gratuit să vă ajute și să fie &icirc;ncă un motiv pentru care să simțiți că alegerea Rădăcini vă <span style="color: #004994;">aduce</span> beneficii reale.</span></span></p>
<p style="text-align: center; max-width: 500px; margin: 0 auto;"><span style="color: #004994;"><span style="font-size: 13pt; font-family: Aptos, sans-serif;">Vă mulțumesc, &icirc;ncă o dată, că ne sunteți alături! Conduceți cu grijă și sper să nu &icirc;nt&acirc;mpinați nicio problemă cu mașina dumneavoastră. Dar, dacă aveți nevoie de noi, să știți că suntem aici.<br><br></span></span></p>
<p class="MsoNormal" style="text-align: center; max-width: 500px; margin: 0 auto;"><span style="font-size: 13pt; color: #004994; font-family: Aptos, sans-serif;">Cu apreciere,<br><strong>Darius Madadi</strong><br>CEO Rădăcini Auto</span></p>
